name = "jrmeet-signaling"
main = "src/index.js"
compatibility_date = "2023-10-30"

[build]
command = ""

[[durable_objects.bindings]]
name = "SIGNALING_ROOM"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_classes = ["SignalingRoom"]
